apiVersion: v1
kind: Service
metadata:
  name: rsvp-green
  labels:
    apps: rsvp-green
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    app: rsvp-green
